# Generated by Django 3.1.7 on 2021-03-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
