# Generated by Django 3.1.7 on 2021-03-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_app', '0003_auto_20210316_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.TextField(default=None, null=True),
        ),
    ]
