# Generated by Django 3.1.7 on 2021-03-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_app', '0005_auto_20210316_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.TextField(default='', null=True),
        ),
    ]
