# Generated by Django 3.1.7 on 2021-07-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_app', '0007_auto_20210318_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='card',
        ),
        migrations.AddField(
            model_name='link',
            name='cards',
            field=models.ManyToManyField(related_name='links', to='hub_app.Card'),
        ),
    ]
