# Generated by Django 3.1.7 on 2021-07-02 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub_app', '0008_auto_20210701_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='cards',
            new_name='card',
        ),
    ]
