# Generated by Django 3.1.7 on 2021-07-02 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub_app', '0009_auto_20210701_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='card',
        ),
        migrations.AddField(
            model_name='link',
            name='card',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='hub_app.card'),
            preserve_default=False,
        ),
    ]
