# Generated by Django 3.1.7 on 2021-07-02 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub_app', '0010_auto_20210701_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='card',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hub_app.card'),
        ),
    ]
