# Generated by Django 3.1.7 on 2021-03-25 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('caption', models.CharField(default='', max_length=50)),
                ('position', models.CharField(max_length=5)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook_hook_book_app.card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook_hook_book_app.post'),
        ),
    ]
