# Generated by Django 3.2.6 on 2021-08-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_auto_20210811_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='images/no_image_available.png', upload_to=''),
        ),
    ]
