# Generated by Django 3.1.6 on 2021-03-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camoimage',
            name='brush_size',
            field=models.IntegerField(default=10),
        ),
    ]
