# Generated by Django 3.2 on 2021-04-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=445)),
                ('y', models.IntegerField(default=461)),
                ('image', models.ImageField(default='images/grass.png', upload_to='')),
                ('energy', models.IntegerField(default=5)),
            ],
        ),
    ]
